# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'llistaModuls.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_llistaModuls(object):
    def setupUi(self, llistaModuls):
        llistaModuls.setObjectName("llistaModuls")
        llistaModuls.resize(255, 232)
        self.centralwidget = QtWidgets.QWidget(llistaModuls)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.listWidget.setObjectName("listWidget")
        llistaModuls.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(llistaModuls)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 255, 21))
        self.menubar.setObjectName("menubar")
        llistaModuls.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(llistaModuls)
        self.statusbar.setObjectName("statusbar")
        llistaModuls.setStatusBar(self.statusbar)

        self.retranslateUi(llistaModuls)
        QtCore.QMetaObject.connectSlotsByName(llistaModuls)

    def retranslateUi(self, llistaModuls):
        _translate = QtCore.QCoreApplication.translate
        llistaModuls.setWindowTitle(_translate("llistaModuls", "MainWindow"))
