# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pract4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pausa = QtWidgets.QPushButton(Dialog)
        self.pausa.setGeometry(QtCore.QRect(80, 150, 75, 23))
        self.pausa.setObjectName("pausa")
        self.afegirModul = QtWidgets.QPushButton(Dialog)
        self.afegirModul.setGeometry(QtCore.QRect(200, 150, 75, 23))
        self.afegirModul.setObjectName("afegirModul")
        self.reiniciar = QtWidgets.QPushButton(Dialog)
        self.reiniciar.setGeometry(QtCore.QRect(140, 210, 75, 23))
        self.reiniciar.setObjectName("reiniciar")
        self.play = QtWidgets.QPushButton(Dialog)
        self.play.setGeometry(QtCore.QRect(140, 90, 75, 23))
        self.play.setObjectName("play")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pausa.setText(_translate("Dialog", "Pausa"))
        self.afegirModul.setText(_translate("Dialog", "Afegir Modul"))
        self.reiniciar.setText(_translate("Dialog", "Reiniciar"))
        self.play.setText(_translate("Dialog", "Play"))
